schema_version = "1.0.0"

id = "use_for_rendering_plus"
version = "0.1.0"
name = "View Layer Plus"
tagline = "Quickly check or uncheck view layer's 'Use For Rendering' prop"
maintainer = "Lukas Sabaliauskas <lukas_sabaliauskas@hotmail.com>"
type = "add-on"
tags = ["Compositing"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]